site_name: Brooklyn
site_description: >
  Bootstrap a programming language compiler from command line tools.
site_author: Tomek Czajka

nav:
  - Home: index.md
  - Reference:
    - reference/ascii.md
    - reference/elf.md
    - reference/x86-64.md
  - Old:
    - hello-world.md
    - asm/assembler-overview.md
    - asm/first-version.md
    - asm/hello-asm.md
    - asm/asm-asm.md
    - reference/notation.md
    - reference/x86.md
    - reference/syscalls.md
  - Code repository: https://github.com/tczajka/bootstrap

plugins:
  - mkdocs-homepage-copier

extra_css:
  - style.css

exclude_docs: |
  /Makefile
  /diagrams
  /build
