site_name: Echo to Tetris
site_description: >
  Bootstrap a compiler, and a Tetris game,
  using nothing but command line tools like echo.
site_author: Tomek Czajka

nav:
  - Home: index.md
  - hello-world.md
  - Reference:
    - reference/numbers.md
    - reference/ascii.md
    - reference/elf.md
    - reference/x86.md
    - reference/syscalls.md
  - Code repository: https://github.com/tczajka/bootstrap

plugins:
  - mkdocs-homepage-copier

extra_css:
  - style.css
