domain: tczajka.github.io
url: https://tczajka.github.io
baseurl: /bootstrap
title: Bootstrapping a compiler
author: Tomek Czajka
email: tczajka@gmail.com
description: Bootstrapping a compiler
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  syntax_highligter: rouge

collections:
  steps:
    output: true
    order:
      - first-program.md
  reference:
    output: true
    order:
      - elf.md
      - x86.md
      - syscalls.md

ordered_collections:
  - steps
  - reference
